import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  content: {
    padding: 24,
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100%",
  },
  uploadBox: {
    width: "100%",
    height: 250,
    borderWidth: 2,
    borderStyle: "dashed",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  uploadText: { fontSize: 18, fontWeight: "bold", marginTop: 16 },
  uploadSubtext: { fontSize: 12, color: "#888", marginTop: 8 },
  fileContainer: { width: "100%", alignItems: "center" },
  fileInfoBox: {
    width: "100%",
    backgroundColor: "#fff",
    padding: 24,
    borderRadius: 16,
    alignItems: "center",
    marginBottom: 24,
    elevation: 2,
  },
  fileName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  previewImage: {
    width: 100,
    height: 80,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 8,
  },
  posTitle: {
    marginTop: 24,
    marginBottom: 12,
    fontSize: 14,
    fontWeight: "bold",
    color: "#555",
  },
  posGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
  },
  posButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#f0f0f0",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  posButtonActive: { backgroundColor: "#fff5d7", borderColor: "#FBBC05" },
  posButtonText: { fontSize: 12, color: "#666", fontWeight: "500" },
  posButtonTextActive: { color: "#d99a00", fontWeight: "bold" },
  actionButton: {
    width: "100%",
    padding: 18,
    borderRadius: 8,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  actionButtonText: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  cancelButton: { marginTop: 16, padding: 8 },
  cancelText: { color: "#888", fontSize: 14 },
  completedBox: { alignItems: "center", width: "100%" },
  completedText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#34A853",
    marginVertical: 16,
  },
});
