import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  content: {
    flex: 1,
    padding: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  uploadBox: {
    width: "100%",
    height: 300,
    borderWidth: 2,
    borderStyle: "dashed",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  uploadText: { fontSize: 20, fontWeight: "bold", marginTop: 16 },
  fileContainer: { width: "100%", flex: 1 },
  listContainer: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    elevation: 2,
  },
  fileRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingVertical: 12,
  },
  fileName: { flex: 1, marginHorizontal: 12, fontSize: 16, color: "#333" },
  addMoreButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    marginTop: 8,
  },
  addMoreText: { color: "#4285F4", fontWeight: "bold", marginLeft: 8 },
  actionButton: {
    width: "100%",
    padding: 18,
    borderRadius: 8,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  actionButtonText: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  cancelButton: { marginTop: 16, padding: 8, alignItems: "center" },
  cancelText: { color: "#888", fontSize: 14 },
  completedBox: { alignItems: "center", width: "100%" },
  completedText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#34A853",
    marginVertical: 16,
  },
});
