import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  centerContent: { flex: 1, padding: 24, justifyContent: "center" },
  scrollContent: { padding: 24, alignItems: "center" },
  uploadBox: {
    width: "100%",
    height: 300,
    borderWidth: 2,
    borderStyle: "dashed",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  uploadText: { fontSize: 20, fontWeight: "bold", marginTop: 16 },
  fileInfoBox: {
    width: "100%",
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 16,
    alignItems: "center",
    marginBottom: 24,
    elevation: 1,
  },
  fileName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  actionButton: {
    width: "100%",
    padding: 18,
    borderRadius: 8,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 24,
  },
  actionButtonText: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  loadingBox: { alignItems: "center", marginVertical: 32 },
  loadingText: { marginTop: 16, color: "#9C27B0", fontWeight: "bold" },
  summaryBox: {
    width: "100%",
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#9C27B0",
    marginBottom: 24,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#9C27B0",
    marginBottom: 12,
  },
  summaryText: { fontSize: 14, color: "#333", lineHeight: 22 },
  cancelButton: { marginTop: 16, padding: 8 },
  cancelText: { color: "#888", fontSize: 14 },
});
