/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/tool/ai`; params?: Router.UnknownInputParams; } | { pathname: `/tool/compress`; params?: Router.UnknownInputParams; } | { pathname: `/tool/merge`; params?: Router.UnknownInputParams; } | { pathname: `/tool/notes`; params?: Router.UnknownInputParams; } | { pathname: `/tool/sign`; params?: Router.UnknownInputParams; } | { pathname: `/tool/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/tool/convert/[type]`, params: Router.UnknownInputParams & { type: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/tool/ai`; params?: Router.UnknownOutputParams; } | { pathname: `/tool/compress`; params?: Router.UnknownOutputParams; } | { pathname: `/tool/merge`; params?: Router.UnknownOutputParams; } | { pathname: `/tool/notes`; params?: Router.UnknownOutputParams; } | { pathname: `/tool/sign`; params?: Router.UnknownOutputParams; } | { pathname: `/tool/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/tool/convert/[type]`, params: Router.UnknownOutputParams & { type: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/tool/ai${`?${string}` | `#${string}` | ''}` | `/tool/compress${`?${string}` | `#${string}` | ''}` | `/tool/merge${`?${string}` | `#${string}` | ''}` | `/tool/notes${`?${string}` | `#${string}` | ''}` | `/tool/sign${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/tool/ai`; params?: Router.UnknownInputParams; } | { pathname: `/tool/compress`; params?: Router.UnknownInputParams; } | { pathname: `/tool/merge`; params?: Router.UnknownInputParams; } | { pathname: `/tool/notes`; params?: Router.UnknownInputParams; } | { pathname: `/tool/sign`; params?: Router.UnknownInputParams; } | `/tool/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tool/convert/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/tool/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/tool/convert/[type]`, params: Router.UnknownInputParams & { type: string | number; } };
    }
  }
}
